### ISSUE TITLE
consider using a logger

### ISSUE THREAD

**Issue by pmlopes** [jaymine/TCP-eventbus-client-C-Sharp#1]
Errors are printed to STDOUT maybe using something like:

https://msdn.microsoft.com/en-us/library/microsoft.build.utilities.logger.aspx

would make more sense to use something like:

http://logging.apache.org/log4net/release/example-apps.html

**Comment by jaymine** [comment]
Updated Eventbus.cs with logger features for errors
https://github.com/jaymine/TCP-eventbus-client-C-Sharp/commit/6bbb44c8433fd78a00ab3efe576f6ee145cf91a7

**Comment by jaymine** [comment]
Updated Testcases
https://github.com/jaymine/TCP-eventbus-client-C-Sharp/commit/2b78210b15a88c11ea2be3e7460ec11b72df0fbe
