### ISSUE TITLE
use a json parser to avoid serialization/parsing errors:

### ISSUE THREAD

**Issue by pmlopes** [jaymine/TCP-eventbus-client-C-Sharp#2]
Look into: `DataContractJsonSerializer` here is an example:

https://msdn.microsoft.com/en-us/library/hh674188.aspx

**Comment by jaymine** [comment]
Fixed issue
Used Json.NET :
http://www.newtonsoft.com/json

1) used using Newtonsoft.Json.Linq;
2) Changed headers and body -> JObjects

**Comment by jaymine** [comment]
3) Changed tests and examples
